### ISSUE TITLE
[Team 3] Demo 1: Dropdown list of booked student

### ISSUE THREAD

**Issue by bit97** [Team1SoftEng2/PULSeBS_Group1#1]
**:older_man: Archibald: old professor**
I would like to have an icon or some hints about the fact that the lecture row can be expanded to show the list of the booked students.
Thank you

**Comment by NeedlesslyLongUserName** [comment]
We fixed this issue in our last commit "PUL-51 Solved GitHub issues + other small changes", thank you for your feedback
