### ISSUE TITLE
[Team 3] Demo 1: Login Page

### ISSUE THREAD

**Issue by LucaAntoniotti** [Team1SoftEng2/PULSeBS_Group1#2]
🧑‍🎓 Giovanni: design student
I want to congratulate with you for the the login page because it is very well designed, I like expecially the right animated part, what I can suggest to you is to better align the login button with the username and password fields

**Comment by NeedlesslyLongUserName** [comment]
We fixed this issue in our last commit "PUL-51 Solved GitHub issues + other small changes", thank you for your feedback
