### ISSUE TITLE
More detailed student notification for cancelled lecture

### ISSUE THREAD

**Issue by Diddy42** [Team1SoftEng2/PULSeBS_Group1#7]
As a student, when a lecture I booked is cancelled I receive an email with the id of the cancelled lecture.
It would be useful to have more information about the lecture in the email, for example the course and the date.
Thanks!

**Comment by simosina96** [comment]
As a student, I think it would be useful to have detailed information about the lecture in the received email for each operation I do (cancellation, booking...).
